sudo: false
dist: trusty
language: python
python:
    - 2.7
    - 3.6.1
install:
    - pip install flake8  # pytest  # add some tests later
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --statistics
    # exit-zero treates all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script: true
    # pytest --capture=sys    # add some tests later
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
